### ISSUE TITLE
Not showing full answer

### ISSUE THREAD

**Issue by lihkg1518** [skydoves/chatgpt-android#102]
the chat didn't display full answer, it stops in the middle when answers are long.

**Comment by skydoves** [comment]
Hey @lihkg1518, would you provide more details for this? It would be very helpful to provide what question generates a long answer. Thanks!

**Comment by lihkg1518** [comment]
it happens when it answers in Chinese


![english](https://user-images.githubusercontent.com/127570095/224587504-6d0b698f-ac84-4192-83c5-06a0127258ad.png)
![chinese](https://user-images.githubusercontent.com/127570095/224587937-6124d2b4-bdc6-488d-be29-3cf1baec4d0f.png)

**Comment by zekierciyas** [comment]
This problem does not seem to be a UI-based or mobile-based problem as far as I understand. The same problem exists with the use of ChatGPT Web. Response may be interrupted due to server overuse.

**Comment by boust3r** [comment]
To me this happens also in English if the answer is very long. Is there a fix?

**Comment by skydoves** [comment]
Hello everyone, I'm excited to announce that this repository has now migrated to utilize OpenAI's official chat API. Please refer to the [new guidelines](https://github.com/skydoves/chatgpt-android?tab=readme-ov-file#-how-to-build-the-project) for instructions on running this project. Thank you for your attention!
