### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by CMingTseng** [skydoves/chatgpt-android#103]
Dear Sir

i  logcat webview

those step : 

 auth/login?next=/chat

 auth0?prompt=login 

 

 login/identifier?state= 

 login/password?state= 
 

body 

state=hKFo2SBLOHQ0MWVNSEdMWERwaWlLcDI5U05IVWRxS0hjYXZRQ6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIENVQnkyTkNqc2ZkZFZ1ak41aXl6T0I5R1Z1Mi1CLTY3o2NpZNkgVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEc&username=xxxxx&=&js-available=true&webauthn-available=false&is-brave=false&webauthn-platform-available=false&action=default

 /chat

 api/auth/session 

 accounts/check 

 backend-api/models  

 /conversations?offset=0&limit=20 
 
 now  the app stop at "conversations"
 
 so  can not open  default/new chat
 
 THX

**Comment by skydoves** [comment]
The app is working fine. Please check if your free account's trial rate is not reached the limit: https://community.openai.com/t/chatgpt-usage-limits/23920

**Comment by CMingTseng** [comment]
> The app is working fine. Please check if your free account's trial rate is not reached the limit: https://community.openai.com/t/chatgpt-usage-limits/23920
Dear Sir

i create a new GPT account 

init it 

can not  create any  new chat 

THX
