### ISSUE TITLE
CLOUDFLARE ERROR

### ISSUE THREAD

**Issue by rkdrlgh22** [skydoves/chatgpt-android#109]
"CHECK you're human." A bug where you cannot log in no matter how much you proceed with the check mark

**Comment by obedientgoyim** [comment]
I'm having this issue too it just loops between trying to check the browser and captcha verification

**Comment by 4n7hcnyG** [comment]
Same here just keeps looping and asking to check the box and "Verify you are human"

**Comment by skydoves** [comment]
It seems we should bypass Cloudflare to make this app work properly. Let me take a look when I have a moment.

**Comment by skydoves** [comment]
If anyone wants to resolve this issue, PR is always welcome!

**Comment by skydoves** [comment]
This [open-source project](https://github.com/tachiyomiorg/tachiyomi/blob/47a2d066821d0f65680255f5ce6442fd0af55382/core/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt#L21) may already have resolved this issue by bypassing Cloudflare. The project can be a good reference if anyone is interested in working on this.

**Comment by playersct** [comment]
Same here just keeps looping and asking to check the box and "Verify you are human". Galaxy S23+ Android 13

**Comment by skydoves** [comment]
Hey guys, it seems to be working well right now.

**Comment by skydoves** [comment]
Let me close this issue right now. Please leave some comments if you're still facing this issue. Thanks!

**Comment by obedientgoyim** [comment]
Works now! Thanks
