### ISSUE TITLE
can't log in with a Google account 

### ISSUE THREAD

**Issue by tulensayyj** [skydoves/chatgpt-android#110]
the latest version still can't log in with a Google account . Does anyone know how to fix it ?

**Comment by Spectroxx** [comment]
#99 
I've already made a big report about it, it has not yet been fixed by @skydoves

**Comment by skydoves** [comment]
Unfortunately, OpenAI keeps changing the rules of the user agent & Cloudflare. Let me find out if there's another way to resolve this when I have a moment.

**Comment by skydoves** [comment]
On the other hand, PR is always welcome if you want to work on this.

**Comment by skydoves** [comment]
The new release `1.0.8` supports Google Sign-in now.

**Comment by andrwj** [comment]
The 403 Error It still happens in `1.0.8`. 
- Android 8.1
- use Google Account
