### ISSUE TITLE
I can't log in with the error saying password is not correct. But I am typing correctly and can login with web. By the way I am using gmail. 

### ISSUE THREAD

**Issue by 8ithu6** [skydoves/chatgpt-android#112]

**Comment by skydoves** [comment]
For now, this app doesn't support Gmail login. You can log in with your email manually.

**Comment by 8ithu6** [comment]
> For now, this app doesn't support Gmail login. You can log in with your email manually.

Thanks for your response. So I have to use any email but not gmail, right? Any plan to support Gmail in the future release?
