### ISSUE TITLE
Error 400 in version 1.0.8

### ISSUE THREAD

**Issue by andrwj** [skydoves/chatgpt-android#115]
Try to login using Google Account, then 400 Error still happens in 1.0.8 on Android 8.1
After relaunch the app, I can make/join chat room. But get the message "something went wrong..." all the time.

![400_error_in_1 0 8](https://user-images.githubusercontent.com/259207/226097005-ff5e727f-63c3-490c-87a0-b50af1145b17.jpg)

**Comment by mertgoksel** [comment]
Same here samsung s10+

**Comment by dhocnet** [comment]
on me with v1.0.8, cannot login at all. just loop on login green button without open any form.

![Screenshot_20230326-091036.png](https://user-images.githubusercontent.com/29807294/227749861-0c359c14-4faf-4cc4-8a79-46fe700fa4a2.png)

**Comment by SimonB97** [comment]
Same here, Android 12, OP7 pro, 1.0.8

**Comment by skydoves** [comment]
Hello everyone, I'm excited to announce that this repository has now migrated to utilize OpenAI's official chat API. Please refer to the [new guidelines](https://github.com/skydoves/chatgpt-android?tab=readme-ov-file#-how-to-build-the-project) for instructions on running this project. Thank you for your attention!
