### ISSUE TITLE
Can't login with Gmail again with error saying reinstall the app. 

### ISSUE THREAD

**Issue by ghost** [skydoves/chatgpt-android#118]

**Comment by Try64** [comment]
Microsoft Account login does the same.
Scenario is , when I login using microsoft account, the page shows chat-gpt page and right after that starts loading.[loading does not stops]. During this time if I press new chat, it says to re-install the app.

**Comment by Try64** [comment]
> Microsoft Account login does the same. Scenario is , when I login using microsoft account, the page shows chat-gpt page and right after that starts loading.[loading does not stops]. During this time if I press new chat, it says to re-install the app.

solved: my channel permission was not proper. To be specific "Disable Auth Checks" was not turned on.

**Comment by Try64** [comment]
> _No description provided._

please check that your stream channel ensures "Disable Auth Checks" turned on. 
Thanks

**Comment by 8ithu6** [comment]
thanks

**Comment by sunnyswag** [comment]
reference from project README.md
> 4. Then click the Log in button and type your account information like the below. You must log in with your Email address, not your Google or Microsoft account.

**Comment by skydoves** [comment]
Hello everyone, I'm excited to announce that this repository has now migrated to utilize OpenAI's official chat API. Please refer to the [new guidelines](https://github.com/skydoves/chatgpt-android?tab=readme-ov-file#-how-to-build-the-project) for instructions on running this project. Thank you for your attention!
