### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by daadoss** [skydoves/chatgpt-android#119]
It asks me to close and ropen the app or reinstall it.

**Comment by Try64** [comment]
@daadoss , Please check that your stream channel settings . Particularly Disable Auth Checks is turned on.

**Comment by obedientgoyim** [comment]
How do you get into settings on the app? I can't see it anywhere

**Comment by Try64** [comment]
> How do you get into settings on the app? I can't see it anywhere

go to your [stream account](https://dashboard.getstream.io/)  and then go to the app setting . Check the settings for the app which you have created for this android project.

**Comment by LooOOooM** [comment]
@Try64 What?
I am not having a stream account. I just loaded the app few weeks ago, which firstly worked as I was loggin into my chatbotGPT account - Now it is not working anymore. I can login, however any request results in the initial reported error.

**Comment by skydoves** [comment]
Hello everyone, I'm excited to announce that this repository has now migrated to utilize OpenAI's official chat API. Please refer to the [new guidelines](https://github.com/skydoves/chatgpt-android?tab=readme-ov-file#-how-to-build-the-project) for instructions on running this project. Thank you for your attention!
