### ISSUE TITLE
Stream Channel error messages are not showing properly.

### ISSUE THREAD

**Issue by Try64** [skydoves/chatgpt-android#120]
I tried to login, but somehow loading was not stopping. I checked in the console that stream API was sending 401 error. I think that exception from stream is not processed properly.

**Comment by skydoves** [comment]
Hey @Try64, I wonder if your Stream account is still valid or expired the free 30 days trial limits.

**Comment by skydoves** [comment]
I'm also wondering if you enabled the user permissions below on your Stream dashboard:

![Screenshot 2023-03-06 at 9 26 21 AM](https://user-images.githubusercontent.com/24237865/228542503-f421c076-20a0-4e2c-bb41-0c65e0d0222e.png)

![Screenshot 2023-03-29 at 9 56 14 PM](https://user-images.githubusercontent.com/24237865/228542736-8495b1c3-c9b4-499e-9453-3e2e1495945f.png)
