### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by luanon404** [skydoves/chatgpt-android#16]
Support login with mail & password
or
Add Edittext for input parameters
Why: I don't think anyone likes the fact that every time the cf_clearance expires, they have to re-sign the app

**Comment by skydoves** [comment]
Hey @luanon404, I'm working on this.

**Comment by luanon404** [comment]
thanks

**Comment by skydoves** [comment]
Hey @luanon404, released a new version and it includes the login feature. Thanks for reporting this.
