### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Foriyo** [skydoves/chatgpt-android#174]
I have download 1.0.8 amd 1.0.9 but login and Signup buttons are not working. Even the button not showing properly.![Screenshot_2023-06-25_20-29-41.png](https://user-images.githubusercontent.com/76862635/248569299-b7151a64-d831-4f81-819b-380459603dc0.png)

**Comment by XiaoyaWang-gh** [comment]
+1

**Comment by plplmax** [comment]
1.0.11, Google Pixel 6

![Screenshot_20230826-132414.png](https://github.com/skydoves/chatgpt-android/assets/50287455/a429d28f-3245-412a-87cb-ec407e61cc6d)

**Comment by st4ycool** [comment]
This is amazing that you have MAD rating G.O.A.T. but you app is so over-engineered that you can't really use it. You can't event login into it with google. This is fascinating

**Comment by Wangxuechi** [comment]
onec I click login button there is nothing happened

**Comment by skydoves** [comment]
Hello everyone, I'm excited to announce that this repository has now migrated to utilize OpenAI's official chat API. Please refer to the [new guidelines](https://github.com/skydoves/chatgpt-android?tab=readme-ov-file#-how-to-build-the-project) for instructions on running this project. Thank you for your attention!
