### ISSUE TITLE
No reply from GPT dead

### ISSUE THREAD

**Issue by abdulpinto** [skydoves/chatgpt-android#181]
Reinstalled but not getting any reply from Chatgpt

**Comment by ShiroiKuma0** [comment]
Same here - no response. This is a critical issue!

**Comment by shivank-dvlpr** [comment]
Still not getting any Response.

**Comment by achdu0000** [comment]
No response for all the time!!! What's wrong?

**Comment by ds6ga6** [comment]
same here, no reply

**Comment by skydoves** [comment]
Hello everyone, I'm excited to announce that this repository has now migrated to utilize OpenAI's official chat API. Please refer to the [new guidelines](https://github.com/skydoves/chatgpt-android?tab=readme-ov-file#-how-to-build-the-project) for instructions on running this project. Thank you for your attention!
