### ISSUE TITLE
Forbidden: Something went wrong. Please re-install this app.

### ISSUE THREAD

**Issue by CornerScarf2500** [skydoves/chatgpt-android#23]
Something went wrong. Please check out your session and CF_CLEARANCE is valid. When chat after login the microsoft account. App version 1.0.3. Is any solution for this?

![Screenshot_20221214_191144_chatgpt-android](https://user-images.githubusercontent.com/92162334/207592374-39263f5b-7af3-4a5c-979d-bb0a60c18cee.jpg)

**Comment by Felix-Hamcat** [comment]
Same issue here

**Comment by skydoves** [comment]
Do your guys don't get any issues when you use CHatGPT on the web client?

**Comment by skydoves** [comment]
Btw please follow the instruction below:

https://github.com/skydoves/chatgpt-android#%EF%B8%8F-how-to-run-the-application

You should log in with your email, not your Google & Microsoft accounts.

**Comment by skydoves** [comment]
Could you try the recent version? It shows more detailed log messages to resolve issues. Thank!

**Comment by CornerScarf2500** [comment]
> 你能试试最新的版本吗？它显示更详细的日志消息以解决问题。感谢！

It's already the newest (version 1.0.3 )

**Comment by luanon404** [comment]
its chatgpt side problem, network error, error body stream, .....

**Comment by skydoves** [comment]
Released version 1.0.4.

**Comment by CornerScarf2500** [comment]
> 发布版本 1.0.4。

I'm updated my app to version 1.0.4 and still cannot use
![Uploading Screenshot_20221216_184815_chatgpt-android.jpg…]()

**Comment by skydoves** [comment]
Hey, it seems OpenAI has restricted some countries. Check out the [supported-counties](https://beta.openai.com/docs/supported-countries).

**Comment by skydoves** [comment]
In version 1.0.6, it will show you more clarified error messages. Please re-open issues regarding the new errors. Thanks!
