### ISSUE TITLE
[Feature Request] Shared 'popular' prompts + Library/Log + Export features. 

### ISSUE THREAD

**Issue by patrickcurl** [skydoves/chatgpt-android#25]
There's a few chrome extensions that have some of these features. I'm trying to implement it w/ WebViews+Flutter but not really a mobile dev. This app is pretty sleek so would be cool to add these features.

**Comment by skydoves** [comment]
Hey @patrickcurl, sorry for the delayed response. I think one of my great colleagues @Nash0x7E2 may have a similar solution to this. Any idea for this? 😄

**Comment by Nash0x7E2** [comment]
Hey @patrickcurl, this blog post may be of interest to you https://getstream.io/blog/build-flutter-chrome-extension/
