### ISSUE TITLE
It said I sent more than 5000 characters.

### ISSUE THREAD

**Issue by yufeng-liang** [skydoves/chatgpt-android#26]
![Screenshot_2022-12-15-01-07-11-971_com.skydoves.chatgpt.jpg](https://user-images.githubusercontent.com/77224953/207663113-03dfc0ad-70bf-4f5b-9888-1fbeb51d7b6e.jpg)
Like the picture,i just sent it a hi.
I have no idea how to let it work properly

**Comment by skydoves** [comment]
Hey @yufeng-liang, please follow the new building instructions: https://github.com/skydoves/chatgpt-android#-how-to-build-the-project
Thanks!

**Comment by yufeng-liang** [comment]
The problem has been solved. Thank u so much
