### ISSUE TITLE
为什么会答复一堆乱码给我

### ISSUE THREAD

**Issue by lwxzhr** [skydoves/chatgpt-android#28]

**Comment by skydoves** [comment]
I'd appreciate you if you could describe your issue detailed in English. Thanks :)
Also, the responses are based on OpenAI's Chat GPT-3.

**Comment by lwxzhr** [comment]
Why did this chatgpt send me a string of gibberish characters

**Comment by lwxzhr** [comment]
![微信图片_20221215131245](https://user-images.githubusercontent.com/120319145/207782105-d090add7-a1b8-4538-8c75-01416bd17d88.jpg)

**Comment by skydoves** [comment]
Hmm.. I'm not sure. Because this project is just delegating the messages from OpenAI but let me check if there are any issues in this project. Thanks!
