### ISSUE TITLE
decoding error

### ISSUE THREAD

**Issue by baymax55** [skydoves/chatgpt-android#32]
![c01500b6d20e6cfb3c6041a481c67d1](https://user-images.githubusercontent.com/35788491/208013422-4efe7bb4-d110-408e-8faf-4cad58b7958f.jpg)

**Comment by skydoves** [comment]
I guess the system automatically uses other languages if the prompt is in another language. It's worth to try update [accept-language](https://github.com/skydoves/chatgpt-android/blob/main/core-network/src/main/kotlin/com/skydoves/chatgpt/core/network/service/ChatGPTService.kt#L30) to `zh-CN, zh; q = 0.9`.

**Comment by skydoves** [comment]
I just found out this is ChatGPT's problem. They respond to this when you face 403 forbidden errors. I'm just checking about the 403 errors.

**Comment by skydoves** [comment]
Released a new version, 1.0.4.
