### ISSUE TITLE
App won't work on Android 13

### ISSUE THREAD

**Issue by simplest-circuits** [skydoves/chatgpt-android#36]
Hello,
I recognized that the app won't work on Android 13.

After 20-30 times of screen rotation and switched between dark and light mode, the login buttons come up.
I was able to login and afterwards, I can only see a spinning circle and a write button on the bottom right, but nothing happens afterwards.
![IMG_20221216_073645](https://user-images.githubusercontent.com/9512751/208037568-5be4e634-8408-42c4-9541-02a088f4462d.jpg)

**Comment by tauheed0007** [comment]
same issue loading bar running

**Comment by skydoves** [comment]
Hey guys, would you run again with the new release? Thanks!
