### ISSUE TITLE
Forbidden: Something went wrongPlease re-install this app.

### ISSUE THREAD

**Issue by baymax55** [skydoves/chatgpt-android#37]
I reinstall this app again and again, but it's not working for me

![eb4ed88962ceafc02cabec4ca073729](https://user-images.githubusercontent.com/35788491/208052635-0af296f3-67a7-4496-8fcd-8f28b392c1f6.jpg)

**Comment by CornerScarf2500** [comment]
> 我一次又一次地重新安装这个应用程序，但它对我不起作用
> 
> ![eb4ed88962ceafc02cabec4ca073729](https://user-images.githubusercontent.com/35788491/208052635-0af296f3-67a7-4496-8fcd-8f28b392c1f6.jpg)

Me too

**Comment by skydoves** [comment]
Hey, it seems OpenAI has restricted some countries. Check out the [supported-counties](https://beta.openai.com/docs/supported-countries).

**Comment by driuft** [comment]
Seeing the same error - I'm based in the US

**Comment by delta-whiplash** [comment]
Facing same error from France APK version 1.0.3 but downloaded 1.0.4 release

**Comment by kirisakow** [comment]
Related: #23

**Comment by kirisakow** [comment]
Related: #23

**Comment by skydoves** [comment]
In version 1.0.6, it will show you more clarified error messages. Please re-open issues regarding the new errors. Thanks!
