### ISSUE TITLE
Can't log in with Google

### ISSUE THREAD

**Issue by haraop** [skydoves/chatgpt-android#38]
It throws an error:

Error 403: disallowed_useragent 
![Screenshot_20221217_200131_chatgpt-android](https://user-images.githubusercontent.com/20980396/208257992-6f1473ad-0bbc-4ad0-9ec5-a1d705f8ffe4.jpg)

**Comment by skydoves** [comment]
Hey @haraop, please follow the instructions: https://github.com/skydoves/chatgpt-android#%EF%B8%8F-how-to-run-the-application
