### ISSUE TITLE
[Auth][Google] Authorization Error

### ISSUE THREAD

**Issue by driuft** [skydoves/chatgpt-android#39]
**Issue**: Error when attenpting to sign in with Google (`Error 403: disallowed_useragent`)

**Message**:
Access blocked: Authorization Error

You can’t sign in from this screen because this app doesn’t comply with Google’s secure browsers policy. If this app has a website, you can open a web browser and try signing in from there.

You can let the app developer know that this app doesn’t comply with Google’s secure browsers policy.

**Error 403: disallowed_useragent**

**Comment by BAF3C9BDC8CB** [comment]
I had the same problem.

**Comment by driuft** [comment]
The behavior is expected as of right now (based on the README instructions) but I'm wondering if there is a way around this.

**Comment by skydoves** [comment]
Unfortunately, this is not forbidden by OpenAI and there's no clear solution yet.

**Comment by cliuff** [comment]
This issue is most likely caused by Google's [deprecation on in-app WebView sign-in](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html).
To resolve it, we either use the recommended **Chrome Custom Tabs** API, or simply remove WebView identity from WebView's User-Agent string (as shown in below code snippet) to bypass the restriction:
**Example WebView User-Agent:**&nbsp;&nbsp;&nbsp;```Mozilla/5.0 (Linux; Android 11; Pixel 2 XL Build/RP1A.201005.004.A1; wv)```
**With WebView identity stripped:**&nbsp;```Mozilla/5.0 (Linux; Android 11; Pixel 2 XL Build/RP1A.201005.004.A1)```
``` Kotlin
private fun setupWebView() = viewBinding.subPayWebView.run {
    if (providerType == LoginProviderType.Google) {
        // remove wv (web view) from user agent to bypass google oauth web view restriction
        // Mozilla/5.0 (Linux; Android 11; Pixel 2 XL Build/RP1A.201005.004.A1; wv)
        // Mozilla/5.0 (Linux; Android 11; Pixel 2 XL Build/RP1A.201005.004.A1)
        val regex = """(Mozilla/[\d.\s]+\(.+)(;\s*wv)\)""".toRegex()
        settings.userAgentString = settings.userAgentString.replace(regex, "$1)")
    }
}
```

**Comment by dnestico** [comment]
experiencing this error too :/

**Comment by rainbowjose** [comment]
Same problem

**Comment by Poseiden** [comment]
Any solution there? I have met the same problem.

**Comment by skydoves** [comment]
Hey folks, in the new release [1.0.7](https://github.com/skydoves/chatgpt-android/releases/tag/1.0.7), it's available to sign in with Google/Microsoft on this application. Thanks for reporting this issue!

**Comment by Poseiden** [comment]
> 

sorry, but the program still report error when I install the latest version.(which about: Error 403: disallowed_useragent)

![7821678417226_ pic](https://user-images.githubusercontent.com/10356133/224212368-a7900d80-dafb-47e8-9304-b4a8c9db58d7.jpg)
