### ISSUE TITLE
app installed toast showed successful but loading bar showing not going forward

### ISSUE THREAD

**Issue by tauheed0007** [skydoves/chatgpt-android#43]

**Comment by tauheed0007** [comment]
@skydoves  please reply this type of screen showing from last 20 minutes
![image](https://user-images.githubusercontent.com/92750415/209467016-1ea25c1a-02b7-4570-9cc7-c81095470830.png)

**Comment by skydoves** [comment]
Hey @tauheed0007, are you building the app by yourself? or just installed from the released page?

**Comment by tauheed0007** [comment]
only;y a loading bar appears on screen from last 30 min

![Uploading image.png…]()

**Comment by tauheed0007** [comment]
> Hey @tauheed0007, are you building the app by yourself? or just installed from the released page?

i just download the app from version control system  fix the issue of firebase like upload the firebase json file in project and run then follow the every step login sucessful but now only loading bar is showing

**Comment by tauheed0007** [comment]
@skydoves  i just download the source code from version control system fix the issue of firebase like upload the firebase json file in project and run then follow the every step login sucessful but now only loading bar is showing

**Comment by skydoves** [comment]
Hey @tauheed0007, it was released a new version. Please run with the new version and open a new issue if you still face the same one. Thank you!
