### ISSUE TITLE
Different release version and binary

### ISSUE THREAD

**Issue by delta-whiplash** [skydoves/chatgpt-android#45]
Hello when I download the 1.0.4 APK from the release section my phone tell me I'm installing the 1.0.3![Screenshot_2023-01-01-21-36-10-91.jpg](https://user-images.githubusercontent.com/39416418/210183952-115caf70-9dc6-4217-adbf-8231b28a457e.jpg)

**Comment by skydoves** [comment]
Hey @delta-whiplash, this issue was fixed in the last release. Thanks!
