### ISSUE TITLE
Getting "Forbidden: Something went wrong. Please re-install this app."

### ISSUE THREAD

**Issue by ekurer** [skydoves/chatgpt-android#47]
Pixel 6a, Android 13
![Screenshot_20230104-144526](https://user-images.githubusercontent.com/60178602/210558147-6706c727-5386-49c7-adac-9eb204daf7c0.png)

**Comment by lishiye-a** [comment]
same problem on my phone

**Comment by blaynescott** [comment]
Same error occuring using the latest APK under Android 13 on a Pixel 6. Excellent concept, I hope this problem is corrected.

**Comment by Aghneel** [comment]
Yeah looks like the app is down

**Comment by kirisakow** [comment]
Related: #23 #37

**Comment by skydoves** [comment]
In version 1.0.6, it will show you more clarified error messages. Please re-open issues regarding the new errors. Thanks!
