### ISSUE TITLE
Impossible to have a proper conversation: previous messages are not remembered

### ISSUE THREAD

**Issue by kirisakow** [skydoves/chatgpt-android#51]
### Expected behavior

As it is stated on chat.openai.com,

> Capabilities: Remembers what user said earlier in the conversation

### Actual behavior

ChatGPT wrapped in `chatgpt-android.apk` does not remember what was earlier said. As if every message the user sends starts a new conversation.

**Comment by s0alqasim1d** [comment]
It actually does start a conversation for every message. I went to the website to see why it doesn't recall what I said and saw so many conversations with one message each
