### ISSUE TITLE
Suddenly getting error about ID

### ISSUE THREAD

**Issue by Aerasyn** [skydoves/chatgpt-android#6]
Suddenly getting error: "Something went wrong. Please check out your session and conversation id is valid"

**Comment by skydoves** [comment]
Hey @Aerasyn, this project is using unofficial APIs so you need to build this project following the steps below:

https://github.com/skydoves/chatgpt-android#%EF%B8%8F-how-to-build-the-project

Also, the session & conversation id can be expired, so I would recommend using the fresh ones when you build.
