### ISSUE TITLE
Error 403: disallowed_useragent

### ISSUE THREAD

**Issue by therealjuanmartinez** [skydoves/chatgpt-android#64]
This is the error I am presented with when attempting to sign in with my Google account using the released app.

**Comment by therealjuanmartinez** [comment]
Version 1.0.6 APK

Request details: response_type=code redirect_uri=https://auth0.openai.com/login/callback state=jlB7VLfXqXHghH6Q4rIXgZQcHs_y8x41 prompt=login client_id=799222349882-ne3i0s9jdm5s0p7ll2d7tlsi1vc1halt.apps.googleusercontent.com access_type=online scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid

**Comment by skydoves** [comment]
#39

**Comment by skydoves** [comment]
Please check out the [How to run the application](https://github.com/skydoves/chatgpt-android#%EF%B8%8F-how-to-run-the-application).

**Comment by skydoves** [comment]
Hey folks, in the new release [1.0.7](https://github.com/skydoves/chatgpt-android/releases/tag/1.0.7), it's available to sign in with Google/Microsoft on this application. Thanks for reporting this issue!
