### ISSUE TITLE
Blank screen on start up

### ISSUE THREAD

**Issue by a-faaeq** [skydoves/chatgpt-android#65]
![Screenshot_20230124_223300_chatgpt-android.jpg](https://user-images.githubusercontent.com/59743720/214436110-725c9c07-ad5f-47e3-a470-0a27ba3dcd4f.jpg)

I don't get the login page when I open the app.

Android 13
Samsung galaxy a22 5g

**Comment by sharicov** [comment]
Same here, Android 13, Redmi note 9s

**Comment by danielphan2003** [comment]
Try install the old version, that should let you login in. After that update to the latest version. You might need to relogin but this time it will properly show the login button

**Comment by skydoves** [comment]
@danielphan2003 Thanks for the nice explanation!
