### ISSUE TITLE
App creating many new chats on ChatGPT website

### ISSUE THREAD

**Issue by BlackusPL** [skydoves/chatgpt-android#70]
I discovered that, this app create new chat on ChatGPT website when you type to ChatGPT from this app. Please do something with this becouse i dont wanna everytime delete useless chats

**Comment by skydoves** [comment]
Hey @BlackusPL, could you elaborate on these?

**Comment by huanghantao** [comment]
I have the same problem

**Comment by BlackusPL** [comment]
> Hey @BlackusPL, could you elaborate on this issue?

If you type to ChatGPT in app, on chatgpt website was creates new chat

![image](https://user-images.githubusercontent.com/45206560/218204274-6a45030b-2d73-493e-9268-6956764d1ef1.png)

**Comment by TrikayDev** [comment]
@skydoves when the result is returned will come with the ID of the conversation, can you upgrade the API so that when you send it, it can include the ID of the conversation? The purpose is that if the conversation exists, the messages will be inside that conversation

**Comment by Novantric** [comment]
@ziuzangdev +1
Both neater and will allow the AI to read to the covo history!

**Comment by ziuzangdev** [comment]
> @ziuzangdev +1 Both neater and will allow the AI to read to the covo history!

Yes, now i just create "fake" feature to chatGPT can remember, but it still make user chatGPT website look badly

**Comment by svn-nguyen-minh-hai-b** [comment]
@skydoves @Novantric @ziuzangdev I had the same problem, did you know how to fix it?
