### ISSUE TITLE
Unable to login through the app via Google

### ISSUE THREAD

**Issue by rollert2** [skydoves/chatgpt-android#76]
Unable to login via the 'Continue with Google' button

It returns back a 'Access Blocked: Authorization Error
![Screenshot_20230210-225457](https://user-images.githubusercontent.com/125108830/218237996-41aae40e-037f-4a88-a0a3-01dfcde882d9.png)

**Comment by zgq105** [comment]
I also encountered the same problem

**Comment by skydoves** [comment]
#39. Please check out the [How to run the application](https://github.com/skydoves/chatgpt-android#%EF%B8%8F-how-to-run-the-application).

**Comment by navyfighter12** [comment]
> #39. Please check out the [How to run the application](https://github.com/skydoves/chatgpt-android#%EF%B8%8F-how-to-run-the-application).

Can we have google login fixed? I have a chatgpt plus account that is tied to my Google account. I do not want to create another account. 

Thanks

**Comment by skydoves** [comment]
Hey folks, in the new release [1.0.7](https://github.com/skydoves/chatgpt-android/releases/tag/1.0.7), it's available to sign in with Google/Microsoft on this application. Thanks for reporting this issue!
