### ISSUE TITLE
Chat GPT error 403

### ISSUE THREAD

**Issue by HarryHaiVn** [skydoves/chatgpt-android#83]
i changed id,name, and commonChannelId so i don;t know why this issue? can you help?
![Screen Shot 2023-02-15 at 09 21 54](https://user-images.githubusercontent.com/29951563/218911073-40492d3c-60d7-4a31-95c1-4b0d8b86c709.png)

**Comment by svn-nguyen-minh-hai-b** [comment]
@skydoves can you help me?

**Comment by skydoves** [comment]
Hey guys, could you elaborate on this? If you change the channel Id or something, you also need to update the channel information on your [Stream Dashboard](https://getstream.io/dashboard/).

**Comment by HarryHaiVn** [comment]
Hi @skydoves , if I simply add STREAM_CHAT_SDK (for myself), ID, and role without making any further edits, there still seems to be an error. Are you still able to run it successfully? The first time I ran it, everything was working fine, but some days it starts having problems.

**Comment by skydoves** [comment]
Hey @HarryHaiVn, could you check if the Stream chat's free trial time is not expired?

**Comment by HarryHaiVn** [comment]
@skydoves my trial for this service expires in 26 days on March 14th. I believe we might have a problem with the conversation chat GPT API. You can see the error message that I have logged in here, and I think that is the issue.
![Screen Shot 2023-02-16 at 08 28 02](https://user-images.githubusercontent.com/29951563/219239179-c6e500ac-1f1c-48c5-83be-d8d1340cf27d.png)

**Comment by skydoves** [comment]
@HarryHaiVn @svn-nguyen-minh-hai @svn-nguyen-minh-hai-b Hey guys, I think ChatGPT is forbidding it for specific countries, and it seems I can't help you with this from my side. 

Would you check the supported countries? https://platform.openai.com/docs/supported-countries

**Comment by svn-nguyen-minh-hai** [comment]
@skydoves Okay, thank you. I am from Vietnam, so I think the API may not be supported. :(

**Comment by blue340** [comment]
我来自中国，目前无法直接使ChatGPT，但是借助VPN使用，但是需要再登录失败页面刷新一下，如果您能在登录界面设置一个刷新按钮就好了

**Comment by svn-nguyen-minh-hai-b** [comment]
@blue340 Hi there, I use a VPN to access an app, but I've noticed that it's sometimes unreliable. My suspicion is that the app's API may not support VPN usage.

**Comment by svn-nguyen-minh-hai-b** [comment]
@skydoves @blue340 Sometimes the app works properly, but other times it shows errors.
![image](https://user-images.githubusercontent.com/83394685/220808451-d8a64587-fb2d-4c30-91f4-9c44bdc1e996.png)

**Comment by skydoves** [comment]
@svn-nguyen-minh-hai-b, as you can see from the error message, you've tried too many requests. The free usage data limits follow openAI's rule, so you should check it out.

**Comment by svn-nguyen-minh-hai-b** [comment]
@skydoves I asked 4 questions in one channel, but when I checked the questions on the web page, it displayed 4 separate conversations. Is this correct? Is there a way to make it look like a single conversation on the web?
![Screen Shot 2023-02-24 at 09 17 47](https://user-images.githubusercontent.com/83394685/221076557-9f0169e6-0087-4228-a991-525bf225a029.png)

**Comment by skydoves** [comment]
Let me discuss this issue on #70. Thanks for reporting this issue!
