### ISSUE TITLE
Cannot login, blank screen

### ISSUE THREAD

**Issue by ruperson** [skydoves/chatgpt-android#84]
It writes "Checking your browser" and then this happens.
I tried latest 1.0.6 version as well seveal older ones. 

![Screenshot_20230215-203916_chatgpt-android](https://user-images.githubusercontent.com/34577895/219131605-8a2cce47-b308-4b53-ae37-eb8ab4204ff6.jpg)

![Screenshot_20230215-222814_chatgpt-android](https://user-images.githubusercontent.com/34577895/219132564-b67a31fa-88d3-420f-9291-b2f12d27dbfa.jpg)

**Comment by Arche151** [comment]
I have the same issue :/

**Comment by Serg10** [comment]
same problem here :(

**Comment by Novantric** [comment]
It's like this with every apk version on the releases tab for me :(

**Comment by Stonerveli** [comment]
Same problem here as well

**Comment by skydoves** [comment]
Hey guys, could you please share your country & device information? Thank you!

**Comment by ziuzangdev** [comment]
> It writes "Checking your browser" and then this happens. I tried latest 1.0.6 version as well seveal older ones.
> 
> ![Screenshot_20230215-203916_chatgpt-android](https://user-images.githubusercontent.com/34577895/219131605-8a2cce47-b308-4b53-ae37-eb8ab4204ff6.jpg)
> 
> ![Screenshot_20230215-222814_chatgpt-android](https://user-images.githubusercontent.com/34577895/219132564-b67a31fa-88d3-420f-9291-b2f12d27dbfa.jpg)

-This problem can make because your country not support by OpenAi
P/S: But, if you are not using StreamSDK to store message of user, use must remove it, and then, create yourseft webview and load login page, i went user login completed, you store infor user, then you can login like chatGPT website, not throw any error UwU

**Comment by Serg10** [comment]
I solved the problem disabling adGuard!!it seems block openia site

**Comment by skydoves** [comment]
@Serg10 Thanks for sharing your solution! Now I'm closing this issue. Please try to run in a pure device.
