### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by AnywhereYRS** [skydoves/chatgpt-android#88]
Something went wrong. Place re-lunch or re-install this app!

**Comment by skydoves** [comment]
Hey @AnywhereYRS, would you share the details of the error message? Thanks!

**Comment by AnywhereYRS** [comment]
> 

It happens when we are trying to ask question.And then the App shows ‘Something went wrong. Place re-lunch or re-install this app!’

**Comment by Technochange** [comment]
Installed the January 12th APK.
Attempted to sign in by selecting the Google SSO option
Received the "Access blocked: Authorization Error" 

Error 403: disallowed_useragent
Request details: response_type=code redirect_uri=https://auth0.openai.com/login/callback state=0w38n5XXpSEjI8-KHpLwD7Qb5FhrNuK8 prompt=login client_id=799222349882-ne3i0s9jdm5s0p7ll2d7tlsi1vc1halt.apps.googleusercontent.com access_type=online scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid

Do you have any recommendations or workarounds?

**Comment by skydoves** [comment]
@Technochange, this project currently doesn't support Google sign. I will take a task for that when I have a moment.

**Comment by welpdx** [comment]
I have a similar issue. This happens after not using the app for a while.

![img](https://i.imgur.com/gIOGgdp.gif)

Signed in via Email account (not Google SSO). 


Works fine after: closing the app and restarting it -> reprompted to login -> after logging [it works fine again](https://i.imgur.com/QRRn7Iq.png)

**Comment by Technochange** [comment]
No worries. I understand

**Comment by mohammaddvi** [comment]
@skydoves I'm interested in to contribute on this project. May I spend time on this issue if you think it's important and worth to fix?

**Comment by skydoves** [comment]
Hey @mohammaddvi, of course, PR is always welcome!

**Comment by skydoves** [comment]
Hey folks, in the new release [1.0.7](https://github.com/skydoves/chatgpt-android/releases/tag/1.0.7), it's available to sign in with Google/Microsoft on this application.

**Comment by skydoves** [comment]
Please re-open this issue if you same the same problem in the new release. Thanks!
