### ISSUE TITLE
Can't send a message 

### ISSUE THREAD

**Issue by 808eugene** [skydoves/chatgpt-android#9]
Response: Something went wrong. Please check out your session and conversation id is valid.

**Comment by newtonsart** [comment]
I have the same problem, and I did everything it told me to build the project.

**Comment by skydoves** [comment]
Sorry for the confusion. You need to follow step #6 to execute ChatGPT properly. I just removed the download guidelines.

**Comment by newtonsart** [comment]
yes, i did it. Still not working

**Comment by skydoves** [comment]
It seems they're scaling their system because of high demand.

![Screen Shot 2022-12-12 at 11 57 11 PM](https://user-images.githubusercontent.com/24237865/207077688-ff80961d-b37b-4f19-bbf8-a67e2ea494b1.png)
