### ISSUE TITLE
Authentication Error 

### ISSUE THREAD

**Issue by ac121102** [skydoves/chatgpt-android#90]
You can’t sign in from this screen because this app doesn’t comply with Google’s secure browsers policy. If this app has a website, you can open a web browser and try signing in from there.

You can let the app developer know that this app doesn’t comply with Google’s secure browsers policy. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-disallowed-useragent)
If you are a developer of Universe, see [error details](https://accounts.google.com/).
Error 403: disallowed_useragent

**Comment by someisoo** [comment]
+1

**Comment by TheRealLOTM** [comment]
![image](https://user-images.githubusercontent.com/76136648/222859679-c1f98279-7b78-4742-9867-0cc31c0f626a.png)
it's like yall don't know how to read

**Comment by TheRealLOTM** [comment]
you can't log in with google or microsoft atm

**Comment by ac121102** [comment]
I checked the issue #39 from last December and opened this issue in case as it's been months with the same issue, either it could be improved or the Google Sign In button could just be removed.

**Comment by skydoves** [comment]
Hey folks, @ac121102, @someisoo, @TheRealLOTM, in the new release [1.0.7](https://github.com/skydoves/chatgpt-android/releases/tag/1.0.7), it's available to sign in with Google/Microsoft on this application. Thanks for reporting this issue!
