### ISSUE TITLE
Error 403 [Ver. 1.0.7]

### ISSUE THREAD

**Issue by Spectroxx** [skydoves/chatgpt-android#99]
Using version [1.0.7](https://github.com/skydoves/chatgpt-android/releases/tag/1.0.7) I am still receiving error 403 when attempting to log in via Google.

Steps to reproduce:

- Download & install version 1.0.7
- Log in via Google
- [Result Image](https://cdn.discordapp.com/attachments/739154431475449856/1082917840631369758/Screenshot_20230308_014823_chatgpt-android.jpg)

I am currently using an S22+ running Android 13.

**Comment by netskycz** [comment]
Same here - Xiaomi 11T Pro, MIUI 14.0.5, Android 13.

**Comment by CrimsonDaddy** [comment]
I have the same issue

**Comment by Spectroxx** [comment]
@skydoves Is this something that can be easily fixed? 

In any other case I'd likely have changed the service linked to my OpenAI account, however that's not something they're supporting at the moment, so we're forced to stick with the service used to create the OpenAI account, in this case Google.

**Comment by skydoves** [comment]
#98

**Comment by Spectroxx** [comment]
> #98

There is no issue with verifying though Cloudflare. It is working perfectly fine for me.
